version: "3.9"

services:
  postgres:
    image: postgres:17.1
    container_name: strangers_meet_container
    restart: always
    environment:
      POSTGRES_USER: k
      POSTGRES_PASSWORD: k
      POSTGRES_DB: strangers_meet_db
    ports:
      - "5432:5432" # Exposes PostgreSQL on localhost:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data even if the container is restarted

volumes:
  postgres_data: